apiVersion: apps/v1
kind: Deployment
metadata:
  name: md-deoloy-test
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: reactapp
        image: materialdashdemo.azurecr.io/mdproject
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
      imagePullSecrets:
        - name: myregistrykey

---

apiVersion: v1
kind: Service
metadata:
  name: md-lb-svc
  labels:
    app: mydeployment
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: nginx
